import json

posts = [
    {"id": 1, "text": "The wild fox species is highly adaptable and can survive in various environments."},
    {"id": 2, "text": "Vulpes vulpes, commonly known for its bushy tail, is a master of stealth."},
    {"id": 3, "text": "Canis lupus is a highly social predator that hunts in packs in the wilderness."},
    {"id": 4, "text": "The domestic canine is often considered man's best friend, enjoying playtime in local parks."},
    {"id": 5, "text": "Equus caballus has been used by humans for centuries for transport and agriculture."},
    {"id": 6, "text": "The massive gray herbivores of the savanna are known for their incredible memory."},
    {"id": 7, "text": "Felis catus is a small domestic carnivorous mammal that loves to chase mice."},
    {"id": 8, "text": "A beautiful insect with colorful wings gracefully landed on a blooming flower."},
    {"id": 9, "text": "Farm poultry, specifically hens, are essential for egg production in rural areas."},
    {"id": 10, "text": "The spotted mammal grazing in the pasture provides most of the world's milk."},
    {"id": 11, "text": "A woolly flock grazing quietly in the green field is a peaceful rural sight."},
    {"id": 12, "text": "The small rodent with a bushy tail was seen gathering acorns in the forest."},
    {"id": 13, "text": "An eight-legged arachnid spun a complex web in the corner of the woodland."},
    {"id": 14, "text": "Majestic big cats of Africa are fierce predators, ruling the food chain."},
    {"id": 15, "text": "The apex predator of the jungle, recognized by its striped coat, prowls silently."},
    {"id": 16, "text": "A large brown omnivore caught a salmon from the rushing river in North America."},
    {"id": 17, "text": "This gentle giant of the ocean feeds entirely on krill and plankton."},
    {"id": 18, "text": "The fastest land animal can accelerate to incredible speeds during a hunt."},
    {"id": 19, "text": "A large primate known for its intelligence and use of tools in the dense jungle."},
    {"id": 20, "text": "The tall, long-necked herbivore reached the highest leaves on the acacia tree."},
    {"id": 21, "text": "A venomous reptile slithered silently across the desert sand."},
    {"id": 22, "text": "This black and white bird cannot fly, but it swims gracefully in icy waters."},
    {"id": 23, "text": "A large amphibious creature basked in the sun on the muddy riverbank."},
    {"id": 24, "text": "The nocturnal bird of prey rotated its head to locate a mouse in the dark."},
    {"id": 25, "text": "A marine mammal known for its playful behavior and high intelligence leaped from the water."},
    {"id": 26, "text": "The colorful parrot mimicked human speech perfectly in the tropical canopy."},
    {"id": 27, "text": "A heavily armored mammal rolled into a ball to protect itself from predators."},
    {"id": 28, "text": "The slow-moving creature spent its entire day hanging upside down in the rainforest."},
    {"id": 29, "text": "A massive flightless bird ran swiftly across the arid outback."},
    {"id": 30, "text": "The large marsupial carried its young in a pouch while hopping away."},
    {"id": 31, "text": "A small prickly mammal curled up defensively in the underbrush."},
    {"id": 32, "text": "The majestic bird of prey soared high above the mountains, scanning for food."},
    {"id": 33, "text": "A brightly colored amphibian warned predators of its toxicity in the damp rainforest."},
    {"id": 34, "text": "The large marine predator with rows of sharp teeth patrolled the reef."},
    {"id": 35, "text": "A small flying mammal navigated the dark cave using echolocation."},
    {"id": 36, "text": "The desert dwelling mammal with humps is perfectly adapted to survive without water."},
    {"id": 37, "text": "A large bovine with curved horns grazed peacefully on the vast plains."},
    {"id": 38, "text": "The clever cephalopod changed its skin color to blend in with the coral reef."},
    {"id": 39, "text": "A small crustacean scuttled sideways along the sandy beach."},
    {"id": 40, "text": "The large aquatic bird scooped up a fish in its massive throat pouch."},
    {"id": 41, "text": "A furry marine mammal floated on its back, cracking a shell with a rock."},
    {"id": 42, "text": "The elusive snow predator, perfectly camouflaged, stalked its prey in the Himalayas."},
    {"id": 43, "text": "A social insect worked tirelessly to gather pollen and nectar for the hive."},
    {"id": 44, "text": "The large, powerful ape beat its chest in a display of dominance."},
    {"id": 45, "text": "A small, burrowing mammal dug an extensive network of tunnels underground."},
    {"id": 46, "text": "The vibrantly colored fish swam defensively among the stinging tentacles of the anemone."},
    {"id": 47, "text": "A large wading bird with pink plumage filtered food from the shallow lagoon."},
    {"id": 48, "text": "The armored reptile patiently waited for prey near the water's edge."},
    {"id": 49, "text": "A small, agile primate leaped effortlessly from branch to branch in Madagascar."},
    {"id": 50, "text": "The massive marine reptile slowly made its way up the beach to lay its eggs."}
]

with open("posts.json", "w") as f:
    json.dump(posts, f, indent=2)

print("Generated posts.json with 50 blog posts.")
